rails/aulos-musica/config/routes.rb
Rails.application.routes.draw do

  resources :lists

  resources :products do
    collection { post :import }
  end

  get 'lists/:list_id/remove_product_id/:product_id' => 'lists#remove_product_id'
end

rails/aulos-musica/app/models/company.rb
class Company < Contact
end

rails/aulos-musica/app/models/contact.rb
class Contact < ActiveRecord::Base
end

rails/aulos-musica/app/models/electronic.rb
class Electronic < Product
end

rails/aulos-musica/app/models/instrument.rb
class Instrument < ActiveRecord::Base
  has_and_belongs_to_many :products, :join_table => "instrumentation", :foreign_key => "products_id"
end

rails/aulos-musica/app/models/list.rb
class List < ActiveRecord::Base
#
  has_and_belongs_to_many :products
  attr_writer :product_token

  def remove_product_id(id)
    self.products.destroy(id)
  end

  def product_token=(ids)
    self.product_ids = ids.split(",")
  end
  def product_token
    self.product_ids
  end
  def products_count
    self.product_ids.count
  end
end

rails/aulos-musica/app/models/livre.rb
class Livre < Product
end

rails/aulos-musica/app/models/partition.rb
class Partition < Product
  has_and_belongs_to_many :instruments, :join_table => "instrumentation", :foreign_key => "instrument_id"
  has_and_belongs_to_many :people, :join_table => "composership", :foreign_key => "contact_id"
end

rails/aulos-musica/app/models/person.rb
class Person < Contact
  has_and_belongs_to_many :products, :join_table => "composership", :foreign_key => "product_id"

  def person_token
    self.name+", "+self.surname
  end
end

rails/aulos-musica/app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :lists

  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)        
      end
    end

  end

  def self.import(file)
    CSV.foreach(file.path,headers: true) do |row|
      product = find_by_id(row["id"]) || new
      product.attributes = row.to_hash
      product.save!
    end

  end
end

rails/aulos-musica/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

rails/aulos-musica/app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show,:edit,:update,:destroy]

  def index
    @lists = List.includes(:products)
    respond_to do |format|
      format.html
      format.json {send_data @list.to_json}
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json {render :json => @list}
    end
  end

  def edit
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice:"List was created"}
        format.json { render :json => @list}
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end
  def remove_product_id
    @list=List.find(params[:list_id])
    @list.remove_product_id(params[:product_id])
    respond_to do |format|
      format.html { redirect_to @list }
      format.json
    end
  end
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html{ redirect_to @list, notice: "List successefully updated"}
        format.json { render :json => @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
  end

  private
  def set_list
      @list = List.find(params[:id])
    end

  def list_params
      params.require(:list).permit(:name, :description, :product_count, :product_token)
    end
end

rails/aulos-musica/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show,:edit,:update,:destroy]

  def index
    @productHeaders=Product.attribute_names
    @products= Product.all
    respond_to do |format|
      format.html
      format.json {send_data @products.to_json}
      format.csv {send_data @products.to_csv}
    end
  end

  def show
  end

  def destroy
  end

  def create
    product = Product.new(product_params)
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice:"Product was created"}
        format.json { render :show, status: :created, location: @product}
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html{ redirect_to @product, notice: "Product successefully updated"}
        format.json { render :json => @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def import
    Product.import(params[:file])
    redirect_to product_url, notice: "Product Imported"
  end

  private

  def set_product
      @product = Product.find(params[:id])
    end

  def product_params
      params.require(:product).permit(:title,:subtitle,:author,:composer,:description,:info,:instrument,:isbn,:manufacturer,:type)
    end
end

rails/aulos-musica/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/aulos-musica/app/helpers/lists_helper.rb
module ListsHelper
end

rails/aulos-musica/app/helpers/product_helper.rb
module ProductHelper
end

rails/aulos-musica/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AulosMusica</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="page">
  <div id="entete">
    <a href="/">Root</a>
    <a href="/products">Produits</a>
    <a href="/lists">Listes</a>
  </div>
  <div id="corps">
    <%= yield %>
  </div>
  <div id="pied">

  </div>
</div>

</body>
</html>

rails/aulos-musica/app/views/lists/_form.html.erb
<%= form_for (@list) do |f| %>
  <div class="name">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="description">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>
  <div class="product_ids">
    <%= f.label :product_token %>
    <%= f.text_field :product_token %>
  </div>
  <div class="submit">
    <%= f.submit "Create" %>
  </div>
<% end %>

rails/aulos-musica/app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

rails/aulos-musica/app/views/lists/destroy.html.erb
<h1>Lists#destroy</h1>
<p>Find me in app/views/lists/destroy.html.erb</p>

rails/aulos-musica/app/views/lists/edit.html.erb
<h1>Edit List</h1>
<%= render "form" %>

rails/aulos-musica/app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p id='notice'>
<%= notice %>
</p>
<%= link_to "New List", new_list_path() %>
<table cellspacing="5" cellpadding="5">
	<thead>
		<tr>
			<% @lists.attribute_names.each do |list| %>
				<th><%=list%></th>
			<%end%>
		</tr>
	</thead>
	<tbody>

		<% @lists.each do |list| %>
			<tr>
				<%list.attributes.each_value do |v|%>
					<td><%=v%></td>
				<%end%>
				<td>
					<%= link_to	"liste", list_path(list) %>
				</td>
				<td>
					<%= list.products_count %>
				</td>
			</tr>
		<%end%>
	</tbody>
</table>

rails/aulos-musica/app/views/lists/new.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>
<%= render 'form' %>

rails/aulos-musica/app/views/lists/show.html.erb
<p>
	<%= notice %>
</p>
<h1 class='rest-in-place' data-url="/lists/<%=@list.id%>" data-object='list' data-placeholder='Enter Name' data-attribute='name'><%=@list.name%></h1>
<div class='rest-in-place' data-url="/lists/<%=@list.id%>" data-object='list' data-placeholder='Enter Descr' data-attribute='description'><%=@list.description%></div>
<%= link_to "Edit List", edit_list_path(@list) %>
<% if @list.products.count > 0%>
	<table id="products">
		<thead>
			<tr>

				<% @list.products.first.attributes.each_key do |cell| %>
					<th>
						<%= cell %>
					</th>
				<% end %>
			</tr>
		</thead>
		<tbody>
			<%@list.products.each do |product|%>
				<tr>
					<%product.attributes.each_value do |cell|%>
						<td><%=cell%></td>
					<%end%>
					<td>
						<%= link_to "Product", product_path(product) %>
					</td>
					<td>
						<a href="/lists/<%=@list.id%>/remove_product_id/<%=product.id%>">Remove from List</a>

					</td>
				</tr>
				<%end%>
		</tbody>
	</table>
	<% else  %>
<%end %>

rails/aulos-musica/app/views/products/_form.html.erb
<%= form_for @product do |f|%>
  <div class="title">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="subtitle">
    <%= f.label :subtitle %>
    <%= f.text_field :subtitle %>
  </div>
  <div class="author">
    <%= f.label :author %>
    <%= f.text_field :author %>
  </div>
  <div class="composer">
    <%= f.label :composer %>
    <%= f.text_field :composer %>
  </div>
  <div class="description">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div class="info">
    <%= f.label :info %>
    <%= f.text_field :info %>
  </div>
  <div class="instrument">
    <%= f.label :instrument %>
    <%= f.text_field :instrument %>
  </div>
  <div class="isbn">
    <%= f.label :isbn %>
    <%= f.text_field :isbn %>
  </div>
  <div class="manufacturer">
    <%= f.label :manufacturer %>
    <%= f.text_field :manufacturer %>
  </div>
  <div class="type">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <%= f.submit %>

<%end %>

rails/aulos-musica/app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render "form" %>

rails/aulos-musica/app/views/products/index.html.erb
<h1>Product#index</h1>
<div id="product import">
	<%= form_tag import_products_path, multipart: true do %>
	  <%= file_field_tag :file%>
	  <%= submit_tag "Import"%>
	<% end -%>
</div>

<table>
	<thead>
		<%- @productHeaders.each do |header|%>
			<th><%=header%></th>
		<%end%>
	</thead>
	<tbody>
		<% @products.each do |product|%>
			<tr>
				<%- product.attributes.each do |k,v|%>
					<td class='rest-in-place' data-url='/products/<%=product.id%>' data-object='product' data-attribute='<%=k%>'>
						<%= v %>
					</td>
				<%end-%>
			</tr>
		<%end-%>
	</tbody>
</table>

rails/aulos-musica/app/views/products/show.html.erb
<h1>Product</h1>
<% @product.attributes.each do |k,v|%>
<div>
	<span class="k"><%=k%> : </span> <span class="v"><%=v%></span>
</div>
<%end%>
<%= link_to "Edit Me", edit_product_path(@product) %>